# Generated by Django 4.2.9 on 2024-05-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catat', '0003_userprofile_loginsessionstrack_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsessionstrack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catat.userprofile'),
        ),
    ]
