# Generated by Django 4.2.9 on 2024-05-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catat', '0006_rename_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
