# Generated by Django 4.2.9 on 2024-05-24 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catat', '0007_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsessionstrack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
