# Generated by Django 4.2.9 on 2024-05-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catat', '0008_alter_loginsessionstrack_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
