# Generated by Django 4.2.9 on 2024-05-16 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resep', '0008_barangjadi_master_roti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(max_length=100)),
                ('pesanan', models.JSONField()),
                ('tanggal_pesan', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_harga', models.IntegerField()),
                ('total_bayar', models.IntegerField()),
                ('harga_modal', models.IntegerField()),
                ('nomor_telp', models.CharField(max_length=100)),
                ('catatan', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_barang_jadi', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('barang_jadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resep.barangjadi')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_pesanan', to='pesan.pesanan')),
            ],
        ),
    ]
