# Generated by Django 4.2.9 on 2024-05-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='alamat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='harga_modal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='nomor_telp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='total_bayar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='total_harga',
            field=models.IntegerField(default=0),
        ),
    ]
