# Generated by Django 4.2.9 on 2024-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0002_alter_pesanan_alamat_alter_pesanan_catatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='harga_modal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='pesanan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='total_bayar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='total_harga',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
