# Generated by Django 4.2.9 on 2024-07-02 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0003_alter_pesanan_harga_modal_alter_pesanan_pesanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='tanggal_pesan',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
