# Generated by Django 2.2 on 2024-02-18 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KomposisiRoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resep.BahanBaku')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bahan_baku', models.ManyToManyField(through='resep.KomposisiRoti', to='resep.BahanBaku')),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_penjualan', models.DateTimeField(auto_now_add=True)),
                ('roti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resep.Roti')),
            ],
        ),
        migrations.AddField(
            model_name='komposisiroti',
            name='roti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resep.Roti'),
        ),
    ]
