# Generated by Django 4.2.9 on 2024-02-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('hpp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('master_bahan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bahan', models.CharField(blank=True, max_length=100, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_keseluruhan', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_terkecil', models.IntegerField(blank=True, default=0, null=True)),
                ('harga', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_jual', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_kg', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_gram', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('resep', models.ManyToManyField(blank=True, related_name='resep', to='resep.resep')),
            ],
        ),
        migrations.CreateModel(
            name='ListPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarangJadi', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_barang_jadi', models.IntegerField(blank=True, default=0, null=True)),
                ('Pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pesanan', to='resep.pesanan')),
            ],
        ),
    ]
