# Generated by Django 4.2.9 on 2024-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='resep',
        ),
        migrations.AddField(
            model_name='resep',
            name='bahan',
            field=models.ManyToManyField(related_name='bahan_resep', to='resep.bahan'),
        ),
    ]
