# Generated by Django 4.2.9 on 2024-02-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbahan',
            name='resep',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='kode_barang',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='nama',
        ),
        migrations.AddField(
            model_name='barangjadi',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resep',
            name='barang_jadi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BarangJadi', to='resep.barangjadi'),
        ),
        migrations.AddField(
            model_name='resep',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resep',
            name='jumlah_pemakaian',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='master_bahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MasterBahan', to='resep.masterbahan'),
        ),
    ]
