# Generated by Django 2.2 on 2024-02-27 05:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangJadi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('hpp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='harga_gram',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='harga_jual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='harga_kg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='kode_bahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='qty_keseluruhan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='qty_terkecil',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterbahan',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='kode_barang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='master_bahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterbahan',
            name='harga',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='masterbahan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='masterbahan',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterbahan',
            name='resep',
            field=models.ManyToManyField(blank=True, related_name='resep', to='resep.Resep'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ListPesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarangJadi', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_barang_jadi', models.IntegerField(blank=True, default=0, null=True)),
                ('Pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pesanan', to='resep.Pesanan')),
            ],
        ),
        migrations.AddField(
            model_name='resep',
            name='Barang_jadi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Barang_jadi', to='resep.BarangJadi'),
            preserve_default=False,
        ),
    ]
