# Generated by Django 2.2 on 2024-02-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0002_remove_bahan_resep_resep_bahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resep',
            name='Barang_jadi',
        ),
    ]
