# Generated by Django 4.2.9 on 2024-03-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0002_remove_masterbahan_resep_remove_resep_kode_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangjadi',
            name='daftar_bahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
