# Generated by Django 4.2.9 on 2024-03-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0003_barangjadi_daftar_bahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangjadi',
            name='daftar_bahan',
        ),
        migrations.AddField(
            model_name='barangjadi',
            name='daftar_bahan',
            field=models.ManyToManyField(related_name='BarangJadi_daftar_bahan', to='resep.masterbahan'),
        ),
    ]
