# Generated by Django 4.2.9 on 2024-03-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0004_remove_barangjadi_daftar_bahan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangjadi',
            name='daftar_bahan',
        ),
        migrations.AlterField(
            model_name='resep',
            name='barang_jadi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resep', to='resep.barangjadi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resep',
            name='jumlah_pemakaian',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resep',
            name='master_bahan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resep', to='resep.masterbahan'),
            preserve_default=False,
        ),
    ]
