# Generated by Django 4.2.9 on 2024-03-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0005_remove_barangjadi_daftar_bahan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangjadi',
            name='daftar_bahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='barang_jadi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BarangJadi', to='resep.barangjadi'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='jumlah_pemakaian',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='master_bahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MasterBahan', to='resep.masterbahan'),
        ),
    ]
