# Generated by Django 4.2.9 on 2024-04-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0006_barangjadi_daftar_bahan_alter_resep_barang_jadi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangjadi',
            name='daftar_bahan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
