# Generated by Django 4.2.9 on 2024-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0007_alter_barangjadi_daftar_bahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangjadi',
            name='master_roti',
            field=models.BooleanField(default=False),
        ),
    ]
