# Generated by Django 4.2.9 on 2024-05-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0008_barangjadi_master_roti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListPesanan',
        ),
        migrations.DeleteModel(
            name='Pesanan',
        ),
    ]
