# Generated by Django 4.2.9 on 2024-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0009_delete_listpesanan_delete_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangjadi',
            name='hpp',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
