# Generated by Django 4.2.9 on 2024-06-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0010_alter_barangjadi_hpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanOlahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_keseluruhan', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_terkecil', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_kg', models.IntegerField(blank=True, default=0, null=True)),
                ('harga_gram', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResepBahanOlahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bahan_olahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BahanOlahan', to='resep.bahanolahan')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resep', to='resep.resep')),
            ],
        ),
    ]
