# Generated by Django 4.2.9 on 2024-06-24 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resep', '0012_historicalresepbahanolahan_historicalresep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResepBahanJadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pemakaian', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoricalResep',
            new_name='HistoricalResepBahanJadi',
        ),
        migrations.AlterModelOptions(
            name='historicalresepbahanjadi',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resep bahan jadi', 'verbose_name_plural': 'historical resep bahan jadis'},
        ),
        migrations.RemoveField(
            model_name='barangjadi',
            name='master_roti',
        ),
        migrations.RemoveField(
            model_name='historicalbarangjadi',
            name='master_roti',
        ),
        migrations.RemoveField(
            model_name='historicalresepbahanolahan',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='historicalresepbahanolahan',
            name='resep',
        ),
        migrations.RemoveField(
            model_name='resepbahanolahan',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='resepbahanolahan',
            name='resep',
        ),
        migrations.AddField(
            model_name='historicalresepbahanolahan',
            name='barang_jadi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resep.barangjadi'),
        ),
        migrations.AddField(
            model_name='resepbahanolahan',
            name='barang_jadi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resep_bahan_olahan_set', to='resep.barangjadi'),
        ),
        migrations.AlterField(
            model_name='resepbahanolahan',
            name='bahan_olahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep_bahan_olahan_set', to='resep.bahanolahan'),
        ),
        migrations.DeleteModel(
            name='Resep',
        ),
        migrations.AddField(
            model_name='resepbahanjadi',
            name='barang_jadi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resep_bahan_jadi_set', to='resep.barangjadi'),
        ),
        migrations.AddField(
            model_name='resepbahanjadi',
            name='master_bahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resep_bahan_jadi_set', to='resep.masterbahan'),
        ),
    ]
