# Generated by Django 4.2.9 on 2024-06-24 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resep', '0013_resepbahanjadi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalResepBahanOlahan',
            new_name='HistoricalResepOlahanJadi',
        ),
        migrations.RenameModel(
            old_name='ResepBahanOlahan',
            new_name='ResepOlahanJadi',
        ),
        migrations.AlterModelOptions(
            name='historicalresepolahanjadi',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resep olahan jadi', 'verbose_name_plural': 'historical resep olahan jadis'},
        ),
    ]
