# Generated by Django 4.2.9 on 2024-06-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0014_rename_historicalresepbahanolahan_historicalresepolahanjadi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanolahan',
            name='harga',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bahanolahan',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbahanolahan',
            name='harga',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbahanolahan',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
