# Generated by Django 4.2.9 on 2024-06-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0015_bahanolahan_harga_bahanolahan_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresepolahanjadi',
            name='jumlah_pemakaian',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='resepolahanjadi',
            name='jumlah_pemakaian',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
