# Generated by Django 4.2.9 on 2024-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0018_alter_barangjadi_hpp_alter_historicalbarangjadi_hpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangjadi',
            name='hpp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbarangjadi',
            name='hpp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterbahan',
            name='harga_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='masterbahan',
            name='harga_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
